name: Update

on:
  push:
    branches: [master]
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
        
      - name: Update README
        run: |
           export TOKEN="${{ secrets.TOKEN }}"
           deno run --allow-env --allow-net --allow-read --allow-write update/generate.ts
      
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "Readme Update"
          git config --global user.email "mail@example.com"

          git add .
          git commit -m "$(curl -s whatthecommit.com/index.txt)"
          git push
