name: Update

on:
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Abandon Deno
        run: echo "no"
      
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "Readme Update"
          git config --global user.email "mail@example.com"

          git add .
          git commit -m "$(curl -s whatthecommit.com/index.txt)"
          git push
